language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"


script:
  - docker --version # print the version for logging
  - docker-compose -f docker-compose-build.yaml build --parallel
  - docker tag udagram-api-feed ukeh11/udagram-api-feed:v4
  - docker tag udagram-api-user ukeh11/udagram-api-user:v4
  - docker tag udagram-frontend:local ukeh11/udagram-frontend:v4
  - docker tag reverseproxy ukeh11/reverseproxy:v4
# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push ukeh11/udagram-api-feed
  - docker push ukeh11/udagram-api-user
  - docker push ukeh11/udagram-frontend
  - docker push ukeh11/reverseproxy