apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
spec:
  selector:
    matchLabels:
      run: backend-feed
  template:
    metadata:
      labels:
        run: backend-feed
    spec:
      containers:
      - name: backend-feed
        image: docker.io/ukeh11/udagram-api-feed:v4
        env:
        - name: POSTGRES_HOST
          value: "micro.c4kotlgv5jcg.us-east-1.rds.amazonaws.com"
        - name: POSTGRES_DB
          value: "postgres"
        - name: POSTGRES_USERNAME
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"
          - name: AWS_BUCKET
          value: "project-3-dev"
        - name: AWS_REGION
          value: "us-east-1"
        - name: AWS_PROFILE
          value: "default"
        - name: JWT_SECRET
          value: "tsadasdasdsfdsfss"
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: backend-feed
  name: backend-feed
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    service: backend-feed