apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram
  labels:
    app: udagram
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram
  template:
    metadata:
      labels:
        app: udagram
    spec:
      containers:
      - name: udagram-api-feed
        image: ukeh11/udagram-api-feed
      - name: udagram-api-user
        image: ukeh11/udagram-api-user
      - name: udagram-frontend
        image: ukeh11/udagram-frontend
        ports:
        - containerPort: 8100:80
      - name: reverseproxy
        image: ukeh11/reverseproxy
        ports:
        - containerPort: 8080:8080